 -- SELECT * FROM UGYFEL

CREATE TABLE UGYFEL_MASKOLT
(LOGIN NVARCHAR(50) PRIMARY KEY,
EMAIL NVARCHAR(100) MASKED WITH (FUNCTION = 'email()'),
NEV NVARCHAR(100) MASKED WITH (FUNCTION = 'partial(1,"XXX",1)'),
SZULEV INT MASKED WITH (FUNCTION = 'random(1,1000)'),
NEM NVARCHAR(10),
CIM NVARCHAR(100) MASKED WITH (FUNCTION = 'default()')
)

INSERT INTO UGYFEL_MASKOLT
SELECT * FROM UGYFEL

-- SELECT * FROM UGYFEL_MASKOLT

CREATE USER MaskUser WITHOUT Login
GRANT SELECT ON UGYFEL_MASKOLT TO MaskUser

EXECUTE AS User= 'MaskUser'
SELECT * FROM UGYFEL_MASKOLT
REVERT

SELECT OBJECT_NAME(OBJECT_ID) TableName, 
Name ,
is_masked,
masking_function
FROM sys.masked_columns